import { MediaMatcher } from '@angular/cdk/layout';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import {MatDialog, MatDialogRef, MAT_DIALOG_DATA} from '@angular/material/dialog';

@Component({
  selector: 'app-carsbyid',
  templateUrl: './carsbyid.component.html',
  styleUrls: ['./carsbyid.component.sass'],
})
export class CarsbyidComponent implements OnInit {
  params;
  getcar;
  resultsearch;
  daily =false; 
  weeky =false; 
  monthy =false;
  dateObject;

  formC=this.fc.control('')


  ngOnInit(): void {
    this.ar.queryParams.subscribe((params) => {
      this.params = params;
      console.log(params);

      
    });

    // this.getcar=this.getcarss();
    this.resultsearch=this.getcarss().filter(i=>i.id.toString()===this.params.id)
    this.getcar=this.resultsearch;    
    console.log(this.resultsearch,this.getcar)

    this.dateObject = moment('1395-11-22','jYYYY,jMM,jDD');

  }

  getcarss() {
    return [
      {
        id: 1,
        name: 'toyota-camry',
        brand: 'toyota',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/toyota/toyota-camry.jpg',
      },
      {
        id: 2,
        name: 'benz-e350',
        brand: 'benz',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/benz/benz-E350.jpg',
      },
      {
        id: 3,
        name: 'toyota-land cuiser',
        brand: 'toyota',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/toyota/land-cruiser.jpg',
      },
      {
        id: 4,
        name: 'benz-s500',
        brand: 'benz',
        daily: true,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/benz/benz-s500.jpg',
      },
      {
        id: 5,
        name: 'benz-sl63',
        brand: 'benz',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/benz/benz-SL63.jpg',
      },
      {
        id: 6,
        name: 'benz-c200',
        brand: 'benz',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/benz/benz-c200.jpg',
      },
      {
        id: 7,
        name: 'bmw-x1',
        brand: 'bmw',
        daily: true,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/bmw/bmw-x1.jpg',
      },
      {
        id: 8,
        name: 'benz-e350',
        brand: 'benz',
        daily: false,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/benz/benz-E350.jpg',
      },
      {
        id: 9,
        name: 'benz-s500',
        brand: 'benz',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assetimages/cars/benz/benz-s500.jpg',
      },
      {
        id: 10,
        name: 'benz-sl63',
        brand: 'benz',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/benz/benz-SL63.jpg',
      },
      {
        id: 11,
        name: 'benz-c200',
        brand: 'benz',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/benz/benz-c200.jpg',
      },
      {
        id: 12,
        name: 'toyota-prrado',
        brand: 'toyota',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/toyota/prrado-4-door.jpg',
      },
      {
        id: 13,
        name: 'toyota-baby',
        brand: 'toyota',
        daily: true,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/toyota/toyota-baby.jpg',
      },
      {
        id: 14,
        name: 'toyota-tuscon',
        brand: 'toyota',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/toyota/tuscon.jpg',
      },
      {
        id: 15,
        name: 'toyota-land cuiser',
        brand: 'toyota',
        daily: false,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/toyota/land-cruiser.jpg',
      },
      {
        id: 16,
        name: 'toyota-prrado',
        brand: 'toyota',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/toyota/prrado-4-door.jpg',
      },
      {
        id: 17,
        name: 'toyota-baby',
        brand: 'toyota',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/toyota/toyota-baby.jpg',
      },
      {
        id: 18,
        name: 'bmw-528',
        brand: 'bmw',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-528.jpeg',
      },
      {
        id: 19,
        name: 'bmw-i8',
        brand: 'bmw',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-i8.jpg',
      },
      {
        id: 20,
        name: 'bmw-x4',
        brand: 'bmw',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-x4.jpg',
      },
      {
        id: 21,
        name: 'bmw-528',
        brand: 'bmw',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-528.jpeg',
      },
      {
        id: 22,
        name: 'bmw-i8',
        brand: 'bmw',
        daily: false,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/bmw/bmw-i8.jpg',
      },
      {
        id: 23,
        name: 'bmw-x1',
        brand: 'bmw',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-x1.jpg',
      },
      {
        id: 24,
        name: 'bmw-x4',
        brand: 'bmw',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-x4.jpg',
      },
      {
        id: 25,
        name: 'hyundai-genesis',
        brand: 'hyundai',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/hyu/hyundai-genesis.jpg',
      },
      {
        id: 26,
        name: 'hyundai-santa-fe',
        brand: 'hyundai',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/hyu/hyundai-santa-fe.jpg',
      },
      {
        id: 27,
        name: 'hyundai-sonata',
        brand: 'hyundai',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/hyu/hyundai-sonata.jpg',
      },
      {
        id: 28,
        name: 'porsche-boxster',
        brand: 'porsche',
        daily: false,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/porsche/porsche-boxster.jpg',
      },
      {
        id: 29,
        name: 'porsche-cayenne',
        brand: 'porsche',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/porsche/porsche-cayenne.jpg',
      },
      {
        id: 30,
        name: 'porsche-macan',
        brand: 'porsche',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/porsche/porsche-macan.jpg',
      },
      {
        id: 31,
        name: 'porsche-panamera',
        brand: 'porsche',
        daily: true,
        monthy: false,
        weeky: false,
        img: 'assets/images/cars/porsche/porsche-panamera.jpg',
      },
      {
        id: 32,
        name: 'benz-c200',
        brand: 'benz',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/benz/benz-c200.jpg',
      },
      {
        id: 33,
        name: 'benz-e350',
        brand: 'benz',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/benz/benz-E350.jpg',
      },
      {
        id: 34,
        name: 'benz-s500',
        brand: 'benz',
        daily: true,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/benz/benz-s500.jpg',
      },
      {
        id: 35,
        name: 'benz-sl63',
        brand: 'benz',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/benz/benz-SL63.jpg',
      },
      {
        id: 36,
        name: 'benz-c200',
        brand: 'benz',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/benz/benz-c200.jpg',
      },
      {
        id: 37,
        name: 'benz-e350',
        brand: 'benz',
        daily: false,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/benz/benz-E350.jpg',
      },
      {
        id: 38,
        name: 'benz-s500',
        brand: 'benz',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assetimages/cars/benz/benz-s500.jpg',
      },
      {
        id: 39,
        name: 'benz-sl63',
        brand: 'benz',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/benz/benz-SL63.jpg',
      },
      {
        id: 40,
        name: 'toyota-land cuiser',
        brand: 'toyota',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/toyota/land-cruiser.jpg',
      },
      {
        id: 41,
        name: 'toyota-prrado',
        brand: 'toyota',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/toyota/prrado-4-door.jpg',
      },
      {
        id: 42,
        name: 'toyota-baby',
        brand: 'toyota',
        daily: true,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/toyota/toyota-baby.jpg',
      },
      {
        id: 43,
        name: 'toyota-camry',
        brand: 'toyota',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/toyota/toyota-camry.jpg',
      },
      {
        id: 44,
        name: 'toyota-tuscon',
        brand: 'toyota',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/toyota/tuscon.jpg',
      },
      {
        id: 45,
        name: 'toyota-land cuiser',
        brand: 'toyota',
        daily: false,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/toyota/land-cruiser.jpg',
      },
      {
        id: 46,
        name: 'toyota-prrado',
        brand: 'toyota',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/toyota/prrado-4-door.jpg',
      },
      {
        id: 47,
        name: 'toyota-baby',
        brand: 'toyota',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/toyota/toyota-baby.jpg',
      },
      {
        id: 48,
        name: 'bmw-528',
        brand: 'bmw',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-528.jpeg',
      },
      {
        id: 49,
        name: 'bmw-i8',
        brand: 'bmw',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-i8.jpg',
      },
      {
        id: 50,
        name: 'bmw-x1',
        brand: 'bmw',
        daily: true,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/bmw/bmw-x1.jpg',
      },
      {
        id: 51,
        name: 'bmw-x4',
        brand: 'bmw',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-x4.jpg',
      },
      {
        id: 52,
        name: 'bmw-528',
        brand: 'bmw',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-528.jpeg',
      },
      {
        id: 53,
        name: 'bmw-i8',
        brand: 'bmw',
        daily: false,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/bmw/bmw-i8.jpg',
      },
      {
        id: 54,
        name: 'bmw-x1',
        brand: 'bmw',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-x1.jpg',
      },
      {
        id: 56,
        name: 'bmw-x4',
        brand: 'bmw',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-x4.jpg',
      },
      {
        id: 57,
        name: 'hyundai-genesis',
        brand: 'hyundai',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/hyu/hyundai-genesis.jpg',
      },
      {
        id: 58,
        name: 'hyundai-santa-fe',
        brand: 'hyundai',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/hyu/hyundai-santa-fe.jpg',
      },
      {
        id: 59,
        name: 'hyundai-sonata',
        brand: 'hyundai',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/hyu/hyundai-sonata.jpg',
      },
      {
        id: 60,
        name: 'porsche-boxster',
        brand: 'porsche',
        daily: false,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/porsche/porsche-boxster.jpg',
      },
      {
        id: 61,
        name: 'porsche-cayenne',
        brand: 'porsche',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/porsche/porsche-cayenne.jpg',
      },
      {
        id: 62,
        name: 'porsche-macan',
        brand: 'porsche',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/porsche/porsche-macan.jpg',
      },
      {
        id: 63,
        name: 'porsche-panamera',
        brand: 'porsche',
        daily: true,
        monthy: false,
        weeky: false,
        img: 'assets/images/cars/porsche/porsche-panamera.jpg',
      },
      {
        id: 64,
        name: 'benz-c200',
        brand: 'benz',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/benz/benz-c200.jpg',
      },
      {
        id: 65,
        name: 'benz-e350',
        brand: 'benz',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/benz/benz-E350.jpg',
      },
      {
        id: 66,
        name: 'benz-s500',
        brand: 'benz',
        daily: true,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/benz/benz-s500.jpg',
      },
      {
        id: 67,
        name: 'benz-sl63',
        brand: 'benz',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/benz/benz-SL63.jpg',
      },
      {
        id: 68,
        name: 'benz-c200',
        brand: 'benz',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/benz/benz-c200.jpg',
      },
      {
        id: 69,
        name: 'benz-e350',
        brand: 'benz',
        daily: false,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/benz/benz-E350.jpg',
      },
      {
        id: 70,
        name: 'benz-s500',
        brand: 'benz',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assetimages/cars/benz/benz-s500.jpg',
      },
      {
        id: 71,
        name: 'kia-cerato',
        brand: 'kia',
        daily: false,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/kia/kia-cerato.jpg',
      },
      {
        id: 72,
        name: 'kia-sorento',
        brand: 'kia',
        daily: false,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/kia/kia-sorento.jpg',
      },
      {
        id: 73,
        name: 'optima',
        brand: 'kia',
        daily: true,
        monthy: false,
        weeky: false,
        img: 'assets/images/cars/kia/optima.jpg',
      },
      {
        id: 74,
        name: 'sportage',
        brand: 'kia',
        daily: true,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/kia/sportage.jpg',
      },
      {
        id: 75,
        name: 'benz-sl63',
        brand: 'benz',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/benz/benz-SL63.jpg',
      },
      {
        id: 76,
        name: 'toyota-land cuiser',
        brand: 'toyota',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/toyota/land-cruiser.jpg',
      },
      {
        id: 77,
        name: 'toyota-prrado',
        brand: 'toyota',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/toyota/prrado-4-door.jpg',
      },
      {
        id: 78,
        name: 'toyota-baby',
        brand: 'toyota',
        daily: true,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/toyota/toyota-baby.jpg',
      },
      {
        id: 79,
        name: 'toyota-camry',
        brand: 'toyota',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/toyota/toyota-camry.jpg',
      },
      {
        id: 80,
        name: 'toyota-tuscon',
        brand: 'toyota',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/toyota/tuscon.jpg',
      },
      {
        id: 81,
        name: 'toyota-land cuiser',
        brand: 'toyota',
        daily: false,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/toyota/land-cruiser.jpg',
      },
      {
        id: 82,
        name: 'toyota-prrado',
        brand: 'toyota',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/toyota/prrado-4-door.jpg',
      },
      {
        id: 83,
        name: 'toyota-baby',
        brand: 'toyota',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/toyota/toyota-baby.jpg',
      },
      {
        id: 84,
        name: 'bmw-528',
        brand: 'bmw',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-528.jpeg',
      },
      {
        id: 85,
        name: 'bmw-i8',
        brand: 'bmw',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-i8.jpg',
      },
      {
        id: 86,
        name: 'bmw-x1',
        brand: 'bmw',
        daily: true,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/bmw/bmw-x1.jpg',
      },
      {
        id: 87,
        name: 'bmw-x4',
        brand: 'bmw',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-x4.jpg',
      },
      {
        id: 88,
        name: 'bmw-528',
        brand: 'bmw',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-528.jpeg',
      },
      {
        id: 89,
        name: 'bmw-i8',
        brand: 'bmw',
        daily: false,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/bmw/bmw-i8.jpg',
      },
      {
        id: 90,
        name: 'bmw-x1',
        brand: 'bmw',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-x1.jpg',
      },
      {
        id: 91,
        name: 'bmw-x4',
        brand: 'bmw',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/bmw/bmw-x4.jpg',
      },
      {
        id: 92,
        name: 'hyundai-genesis',
        brand: 'hyundai',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/hyu/hyundai-genesis.jpg',
      },
      {
        id: 93,
        name: 'hyundai-santa-fe',
        brand: 'hyundai',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/hyu/hyundai-santa-fe.jpg',
      },
      {
        id: 94,
        name: 'hyundai-sonata',
        brand: 'hyundai',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/hyu/hyundai-sonata.jpg',
      },
      {
        id: 95,
        name: 'porsche-boxster',
        brand: 'porsche',
        daily: false,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/porsche/porsche-boxster.jpg',
      },
      {
        id: 96,
        name: 'porsche-cayenne',
        brand: 'porsche',
        daily: true,
        monthy: false,
        weeky: true,
        img: 'assets/images/cars/porsche/porsche-cayenne.jpg',
      },
      {
        id: 97,
        name: 'porsche-macan',
        brand: 'porsche',
        daily: true,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/porsche/porsche-macan.jpg',
      },
      {
        id: 98,
        name: 'porsche-panamera',
        brand: 'porsche',
        daily: true,
        monthy: false,
        weeky: false,
        img: 'assets/images/cars/porsche/porsche-panamera.jpg',
      },
      {
        id: 99,
        name: 'kia-cerato',
        brand: 'kia',
        daily: false,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/kia/kia-cerato.jpg',
      },
      {
        id: 100,
        name: 'kia-sorento',
        brand: 'kia',
        daily: false,
        monthy: true,
        weeky: true,
        img: 'assets/images/cars/kia/kia-sorento.jpg',
      },
      {
        id: 101,
        name: 'optima',
        brand: 'kia',
        daily: true,
        monthy: false,
        weeky: false,
        img: 'assets/images/cars/kia/optima.jpg',
      },
      {
        id: 102,
        name: 'sportage',
        brand: 'kia',
        daily: true,
        monthy: true,
        weeky: false,
        img: 'assets/images/cars/kia/sportage.jpg',
      },
      {id:110, name: "تویوتا-land cuiser", brand: "toyota", daily: true, monthy: true, weeky: true, img: "assets/images/cars/toyota/land-cruiser.jpg" },
      {id:111, name: "تویوتا-prrado", brand: "toyota", daily: true, monthy: false, weeky: true, img: "assets/images/cars/toyota/prrado-4-door.jpg" },
      {id:112, name: "تویوتا-baby", brand: "toyota", daily: true, monthy: true, weeky: false, img: "assets/images/cars/toyota/toyota-baby.jpg" },
      {id:113, name: "تویوتا-camry", brand: "toyota", daily: true, monthy: true, weeky: true, img: "assets/images/cars/toyota/toyota-camry.jpg" },
      {id:114, name: "تویوتا-tuscon", brand: "toyota", daily: true, monthy: true, weeky: true, img: "assets/images/cars/toyota/tuscon.jpg" },
      {id:115, name: "تویوتا-land cuiser", brand: "toyota", daily: false, monthy: true, weeky: false, img: "assets/images/cars/toyota/land-cruiser.jpg" },
      {id:116, name: "تویوتا-prrado", brand: "toyota", daily: true, monthy: false, weeky: true, img: "assets/images/cars/toyota/prrado-4-door.jpg" },
      {id:117, name: "تویوتا-baby", brand: "toyota", daily: true, monthy: false, weeky: true, img: "assets/images/cars/toyota/toyota-baby.jpg" },
      {id:102, name: "بنز-c200", brand: "benz", daily: true, monthy: true, weeky: true, img: "assets/images/cars/benz/benz-c200.jpg" },
      {id:103, name: "بنز-e350", brand: "benz", daily: true, monthy: false, weeky: true, img: "assets/images/cars/benz/benz-E350.jpg" },
      {id:104, name: "بنز-s500", brand: "benz", daily: true, monthy: true, weeky: false, img: "assets/images/cars/benz/benz-s500.jpg" },
      {id:105, name: "بنز-sl63", brand: "benz", daily: true, monthy: true, weeky: true, img: "assets/images/cars/benz/benz-SL63.jpg" },
      {id:106, name: "بنز-c200", brand: "benz", daily: true, monthy: true, weeky: true, img: "assets/images/cars/benz/benz-c200.jpg" },
      {id:107, name: "بنز-e350", brand: "benz", daily: false, monthy: true, weeky: false, img: "assets/images/cars/benz/benz-E350.jpg" },
      {id:108, name: "بنز-s500", brand: "benz", daily: true, monthy: false, weeky: true, img: "assetimages/cars/benz/benz-s500.jpg" },
      {id:109, name: "بنز-sl63", brand: "benz", daily: true, monthy: false, weeky: true, img: "assets/images/cars/benz/benz-SL63.jpg" },
      {id:118, name: "bmw-528", brand: "bmw", daily: true, monthy: true, weeky: true, img: "assets/images/cars/bmw/bmw-528.jpeg" },
      {id:119, name: "bmw-i8", brand: "bmw", daily: true, monthy: false, weeky: true, img: "assets/images/cars/bmw/bmw-i8.jpg" },
      {id:120, name: "bmw-x1", brand: "bmw", daily: true, monthy: true, weeky: false, img: "assets/images/cars/bmw/bmw-x1.jpg" },
      {id:121, name: "bmw-x4", brand: "bmw", daily: true, monthy: true, weeky: true, img: "assets/images/cars/bmw/bmw-x4.jpg" },
      {id:122, name: "bmw-528", brand: "bmw", daily: true, monthy: true, weeky: true, img: "assets/images/cars/bmw/bmw-528.jpeg" },
      {id:123, name: "bmw-i8", brand: "bmw", daily: false, monthy: true, weeky: false, img: "assets/images/cars/bmw/bmw-i8.jpg" },
      {id:124, name: "bmw-x1", brand: "bmw", daily: true, monthy: false, weeky: true, img: "assets/images/cars/bmw/bmw-x1.jpg" },
      {id:125, name: "bmw-x4", brand: "bmw", daily: true, monthy: false, weeky: true, img: "assets/images/cars/bmw/bmw-x4.jpg" },
      {id:126, name: "hyundai-genesis", brand: "hyundai", daily: true, monthy: true, weeky: true, img: "assets/images/cars/hyu/hyundai-genesis.jpg" },
      {id:127, name: "hyundai-santa-fe", brand: "hyundai", daily: true, monthy: true, weeky: true, img: "assets/images/cars/hyu/hyundai-santa-fe.jpg" },
      {id:128, name: "hyundai-sonata", brand: "hyundai", daily: true, monthy: true, weeky: true, img: "assets/images/cars/hyu/hyundai-sonata.jpg" },
      {id:129, name: "porsche-boxster", brand: "porsche", daily: false, monthy: true, weeky: true, img: "assets/images/cars/porsche/porsche-boxster.jpg" },
      {id:130, name: "porsche-cayenne", brand: "porsche", daily: true, monthy: false, weeky: true, img: "assets/images/cars/porsche/porsche-cayenne.jpg" },
      {id:131, name: "porsche-macan", brand: "porsche", daily: true, monthy: true, weeky: true, img: "assets/images/cars/porsche/porsche-macan.jpg" },
      {id:132, name: "porsche-panamera", brand: "porsche", daily: true, monthy: false, weeky: false, img: "assets/images/cars/porsche/porsche-panamera.jpg" },
      {id:133, name: "kia-cerato", brand: "kia", daily: false, monthy: true, weeky: true, img: "assets/images/cars/kia/kia-cerato.jpg" },
      {id:134, name: "kia-sorento", brand: "kia", daily: false, monthy: true, weeky: true, img: "assets/images/cars/kia/kia-sorento.jpg" },
      {id:135, name: "optima", brand: "kia", daily: true, monthy: false, weeky: false, img: "assets/images/cars/kia/optima.jpg" },
      {id:136, name: "sportage", brand: "kia", daily: true, monthy: true, weeky: false, img: "assets/images/cars/kia/sportage.jpg" },

    ];
  }

  mobileQuery: MediaQueryList;

  fillerNav = Array.from({length: 50}, (_, i) => `Nav Item ${i + 1}`);

  fillerContent = Array.from({length: 50}, () =>
      `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
       labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
       laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
       voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
       cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`);

  private _mobileQueryListener: () => void;

  constructor(public dialog:MatDialog,changeDetectorRef: ChangeDetectorRef, media: MediaMatcher,public ar: ActivatedRoute,public fc:FormBuilder) {
    this.mobileQuery = media.matchMedia('(max-width: 600px)');
    this._mobileQueryListener = () => changeDetectorRef.detectChanges();
    this.mobileQuery.addListener(this._mobileQueryListener);
  }


  periodOfReservasion(){
    
    switch (this.formC.value) {
      
      case "daily":
        this.daily=true;
        this.monthy=false;
        this.weeky=false;
        break;

      case "weeky":
        this.daily=false;
        this.monthy=false;
        this.weeky=true;
        break;

      case "monthy":
          this.daily=false;
          this.monthy=true;
          this.weeky=false;
          break;
    
    }
    
  }


}
function moment(arg0: string, arg1: string): any {
  throw new Error('Function not implemented.');
}

function DialogOverviewExampleDialog(DialogOverviewExampleDialog: any, arg1: { width: string; data: { name: any; animal: any; }; }) {
  throw new Error('Function not implemented.');
}

